# Generated by Django 3.1.1 on 2021-02-09 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGPC_ASSO_COM_PRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACP_QUANTITE', models.PositiveIntegerField()),
                ('ACP_PRIX_VENTE', models.FloatField()),
                ('ACP_TAUX_TVA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_CATEGORIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NOM', models.CharField(max_length=40, unique=True)),
                ('CAT_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_MARQUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAR_NOM', models.CharField(max_length=40, unique=True)),
                ('MAR_is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_PARAMETRES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAR_TAUX_TVA', models.FloatField()),
                ('PAR_DELAI_PAIEMENT', models.PositiveIntegerField()),
                ('PAR_DELAI_PREMIER_RAPPEL', models.PositiveIntegerField()),
                ('PAR_DELAI_DEUXIEME_RAPPEL', models.PositiveIntegerField()),
                ('PAR_NBMAX_RDV_JOUR', models.PositiveIntegerField()),
                ('PAR_LIMITE_STOCK', models.PositiveIntegerField()),
                ('PAR_FRAIS_LIVRAISON_PETIT', models.IntegerField()),
                ('PAR_FRAIS_LIVRAISON_MOYEN', models.IntegerField()),
                ('PAR_FRAIS_LIVRAISON_GRANDE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_PRODUIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_NOM', models.CharField(max_length=40)),
                ('PRO_DESCRIPTION', models.TextField(max_length=200)),
                ('PRO_PRIX_CATALOGUE', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('PRO_QUANTITESTOCK', models.PositiveIntegerField()),
                ('PRO_IMAGE', models.ImageField(blank=True, default='', upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('PRO_CATEGORIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_categorie')),
                ('PRO_MARQUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_marque')),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_COMMANDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COM_DATE', models.DateField()),
                ('COM_STATUT', models.CharField(max_length=50)),
                ('COM_NUMEROSUIVI', models.CharField(blank=True, max_length=50)),
                ('COM_FACTURE_DATE', models.DateField(blank=True, null=True)),
                ('COM_FACTURE_STATUT', models.CharField(blank=True, max_length=50, null=True)),
                ('COM_FRAIS_LIVRAISON', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('COM_PRO_ID', models.ManyToManyField(through='catalogue.SGPC_ASSO_COM_PRO', to='catalogue.SGPC_PRODUIT')),
            ],
        ),
    ]
