# Generated by Django 3.1.1 on 2021-02-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SGPC_Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UTI_EMAIL', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('UTI_PRENOM', models.CharField(max_length=30)),
                ('UTI_NOM', models.CharField(max_length=30)),
                ('UTI_DATENAISSANCE', models.DateField()),
                ('UTI_NUMEROTEL', models.CharField(max_length=20, unique=True)),
                ('UTI_RUE', models.CharField(max_length=60)),
                ('UTI_NUMERORUE', models.PositiveIntegerField()),
                ('UTI_CODEPOSTALE', models.PositiveIntegerField()),
                ('UTI_LOCALITE', models.CharField(max_length=30)),
                ('UTI_is_deleted', models.BooleanField(default=False)),
                ('UTI_is_active', models.BooleanField(default=True)),
                ('UTI_is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
