# Generated by Django 3.1.4 on 2021-03-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_CODEPOSTALE',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_DATENAISSANCE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_NUMERORUE',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
