# Generated by Django 3.1.4 on 2021-03-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20210308_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgpc_utilisateur',
            name='UTI_CODEPOSTALE',
        ),
        migrations.RemoveField(
            model_name='sgpc_utilisateur',
            name='UTI_NUMERORUE',
        ),
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_DATENAISSANCE',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
