# Generated by Django 3.1.4 on 2021-03-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_auto_20210308_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_DATENAISSANCE',
            field=models.DateField(null=True),
        ),
    ]
