# Generated by Django 3.1.4 on 2021-03-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_auto_20210310_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgpc_utilisateur',
            name='UTI_DATENAISSANCE',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
