# Generated by Django 3.1.1 on 2021-02-09 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SGPC_DEVIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEV_DATE', models.DateField(auto_now_add=True)),
                ('DEV_UTI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SGPC_RESERVATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RES_DATE', models.DateField(validators=[service.models.validate_date])),
                ('RES_STATUT', models.CharField(choices=[('Confirmé', 'Confirmé'), ('En attente de confirmation', 'En attente de confirmation'), ('Annulé', 'Annulé')], max_length=50)),
                ('RES_COM_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.sgpc_commande')),
                ('RES_DEV_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.sgpc_devis')),
                ('RES_UTI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
